config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# to display static media files
# only to be used when in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
]

# django allows variables in url paths
# hence int:pk is where the id of the room will go for room details

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:secret>", views.complete_verification, name="complete_verification"
    ),
    path("login/github", views.github_login, name="github_login"),
    path("login/github/callback", views.github_callback, name="github_callback"),
    path("login/gmail", views.gmail_login, name="gmail_login"),
    path("login/gmail/callback", views.gmail_callback, name="gmail_callback"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 font-medium text-gray-600 border-t">
    &copy; 2020 Nbnb, Inc. All rights reserved.
</footer>

templates/partials/nav.html
<ul class="flex items-center text-sm font-bold h-full">

  {% comment %}
  <!-- wodering how nav html has access to the user?
  it is cuz django has something called context processors --> {% endcomment %}

  {% if user.is_authenticated %}
  <li class="nav_link hover:border-gray-600"><a href="{% url 'users:logout' %}">Log out</a></li>
  {% else %}
  <li class="nav_link hover:border-gray-600"><a href="{% url 'users:login' %}">Login</a></li>
  <li class="nav_link hover:border-gray-600"><a href="{% url 'users:signup' %}">Sign Up</a></li>
  {% endif %}
</ul>

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 rounded-md bg-cover mb-2 bg-center" style="background-image:url('{{room.first_photo}}');"></div>
        <div class="flex justify-between items-center mb-2">
            <div class="w-4/5 truncate block">
                {% if room.host.superhost %}
                    <span class="uppercase mr-px px-1 py-0.5 font-medium text-xs border text-black border-black rounded-sm">superhost</span>
                {% endif %}
                <span class="text-sm text-gray-600 font-light">{{room.city}}, {{room.country.name}}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-xs mr-1 text-red-500"></i>{{room.total_rating}}
            </span>
        </div>
        <span class="text-black w-11/12 truncate block">{{room.name}}</span>
    </a>
</div>


{% comment %} the below url is same as this string /rooms/{{room.pk}} {% endcomment %}
    {% comment %} <a href="{% url 'rooms:detail' room.pk%}">
        {{room.pk}}- {{room.name}} - {{room.price}}
    </a> {% endcomment %}

templates/partials/social_login.html
<div class="flex flex-col ">
    <a href="{% url 'users:github_login' %}" class="w-full py-5 mb-5 text-gray-700 font-bold border-2 border-gray-700 text-center rounded-md">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>
        Continue with Github
    </a>

    <a href="{% url 'users:gmail_login' %}" class="w-full text-black mb-2 py-5 font-bold bg-blue-400 border-2 border-black text-center rounded-md">
        <i class="fab fa-google mr-2 fa-lg"></i>
        Continue with Gmail
    </a>
</div>