config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# to display static media files
# only to be used when in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
]

# django allows variables in url paths
# hence int:pk is where the id of the room will go for room details

templates/base.html
{% comment %} django.template.exceptions.TemplateSyntaxError:
 Invalid block tag on line 13: 'static'.
 Did you forget to register or load this tag?
 To resolve this we have to load the tag as done below {% endcomment %}

 {% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block page_name %} {% endblock page_name %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% comment %} href is where it will get css data from which is why creating
    a STATICFILES_DIRS in settings.py was necessary otherwise it would not be
    able to get the data {% endcomment %}

    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
  </head>
  <body class="text-gray-800 mt-24 font-light">
    <header class="container max-w-full inset-0 flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
      <div class="flex items-center w-1/3">
        <a href="{% url 'core:home' %}" class="mr-6">
          <img class="w-8" src="{% static 'img/logo.png' %}">
        </a>
        {% block search_bar %}
        <form method="get" action="{% url 'rooms:search' %}" class="w-9/12">
          <input class=" search-box border w-full shadow-md border-gray-300 px-5 py-3 text-gray-700 placeholder-gray-600 font-medium rounded-sm hover:shadow-lg focus:outline-none" name="city" placeholder="Search by City" />
        </form>
        {% endblock search_bar %}
      </div>
      {% include "partials/nav.html" %}
    </header>
    {% block content %} {% endblock content%} 
    {% include "partials/footer.html"%}
  </body>
</html>